package com.ibm.gps.itoa.portal.model;

public class OperationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_type
     *
     * @mbg.generated
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_user
     *
     * @mbg.generated
     */
    private String operationUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_time
     *
     * @mbg.generated
     */
    private String operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.reagent_name
     *
     * @mbg.generated
     */
    private String reagentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.id
     *
     * @return the value of operation_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.id
     *
     * @param id the value for operation_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_type
     *
     * @return the value of operation_record.operation_type
     *
     * @mbg.generated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_type
     *
     * @param operationType the value for operation_record.operation_type
     *
     * @mbg.generated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_user
     *
     * @return the value of operation_record.operation_user
     *
     * @mbg.generated
     */
    public String getOperationUser() {
        return operationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_user
     *
     * @param operationUser the value for operation_record.operation_user
     *
     * @mbg.generated
     */
    public void setOperationUser(String operationUser) {
        this.operationUser = operationUser == null ? null : operationUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_time
     *
     * @return the value of operation_record.operation_time
     *
     * @mbg.generated
     */
    public String getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_time
     *
     * @param operationTime the value for operation_record.operation_time
     *
     * @mbg.generated
     */
    public void setOperationTime(String operationTime) {
        this.operationTime = operationTime == null ? null : operationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.reagent_name
     *
     * @return the value of operation_record.reagent_name
     *
     * @mbg.generated
     */
    public String getReagentName() {
        return reagentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.reagent_name
     *
     * @param reagentName the value for operation_record.reagent_name
     *
     * @mbg.generated
     */
    public void setReagentName(String reagentName) {
        this.reagentName = reagentName == null ? null : reagentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OperationRecord other = (OperationRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperationType() == null ? other.getOperationType() == null : this.getOperationType().equals(other.getOperationType()))
            && (this.getOperationUser() == null ? other.getOperationUser() == null : this.getOperationUser().equals(other.getOperationUser()))
            && (this.getOperationTime() == null ? other.getOperationTime() == null : this.getOperationTime().equals(other.getOperationTime()))
            && (this.getReagentName() == null ? other.getReagentName() == null : this.getReagentName().equals(other.getReagentName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperationType() == null) ? 0 : getOperationType().hashCode());
        result = prime * result + ((getOperationUser() == null) ? 0 : getOperationUser().hashCode());
        result = prime * result + ((getOperationTime() == null) ? 0 : getOperationTime().hashCode());
        result = prime * result + ((getReagentName() == null) ? 0 : getReagentName().hashCode());
        return result;
    }
}